/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current configuration
         * @description Retrieves the raw YAML configuration with metadata
         */
        get: operations["getConfig"];
        put?: never;
        /**
         * Update configuration
         * @description Updates the plexus.yaml configuration file with validation and optional hot reload.
         */
        post: operations["updateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system state
         * @description Returns current debug settings, cooldowns, and provider metrics
         */
        get: operations["getState"];
        put?: never;
        /**
         * Execute state action
         * @description Execute runtime commands to modify system state.
         */
        post: operations["updateState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query logs
         * @description Query log entries with filters and pagination
         */
        get: operations["queryLogs"];
        put?: never;
        post?: never;
        /**
         * Delete logs
         * @description Bulk delete log entries by type, age, or all
         */
        delete: operations["deleteLogs"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get log details
         * @description Retrieve full details for a specific request including usage, errors,
         *     and debug traces.
         */
        get: operations["getLogDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event stream (SSE)
         * @description Server-Sent Events stream for real-time monitoring. Includes usage events,
         *     system logs, state changes, and configuration updates.
         *
         *     Client disconnects automatically after 30 seconds of inactivity (heartbeat).
         *
         *     Max concurrent clients: 10
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StateGetResponse: {
            debug: {
                enabled: boolean;
                captureRequests: boolean;
                captureResponses: boolean;
            };
            cooldowns: {
                provider: string;
                reason: string;
                /** Format: int64 */
                endTime: number;
                remaining: number;
            }[];
            providers: {
                name: string;
                enabled: boolean;
                healthy: boolean;
                cooldownRemaining?: number | null;
                metrics: {
                    avgLatency: number;
                    successRate: number;
                    requestsLast5Min: number;
                };
            }[];
            uptime: number;
            version: string;
        };
        SetDebugAction: {
            /** @enum {string} */
            action: "set-debug";
            payload: {
                enabled: boolean;
            };
        };
        ClearCooldownsAction: {
            /** @enum {string} */
            action: "clear-cooldowns";
            payload?: {
                /** @description Specific provider to clear (omit to clear all) */
                provider?: string;
            };
        };
        EnableProviderAction: {
            /** @enum {string} */
            action: "enable-provider";
            payload: {
                provider: string;
            };
        };
        DisableProviderAction: {
            /** @enum {string} */
            action: "disable-provider";
            payload: {
                provider: string;
            };
        };
        DebugTraceEntry: {
            /** @description Request ID */
            id: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp
             */
            timestamp: string;
            clientRequest: {
                /** @enum {string} */
                apiType: "chat" | "messages" | "gemini";
                body: Record<string, never>;
                headers: {
                    [key: string]: string;
                };
            };
            providerRequest: {
                /** @enum {string} */
                apiType: "chat" | "messages" | "gemini";
                body: Record<string, never>;
                headers: {
                    [key: string]: string;
                };
            };
            providerResponse?: {
                status?: number;
                headers?: {
                    [key: string]: string;
                };
                body?: Record<string, never>;
                /**
                 * @description Indicates if response is original (non-streaming) or reconstructed from stream chunks
                 * @enum {string}
                 */
                type?: "original" | "reconstructed";
            };
            clientResponse?: {
                status?: number;
                body?: Record<string, never>;
                /**
                 * @description Indicates if response is original (non-streaming) or reconstructed from stream chunks
                 * @enum {string}
                 */
                type?: "original" | "reconstructed";
            };
            providerStreamChunks?: {
                /** Format: date-time */
                timestamp: string;
                /** @description Raw SSE chunk text */
                chunk: string;
            }[];
            clientStreamChunks?: {
                /** Format: date-time */
                timestamp: string;
                /** @description Raw SSE chunk text */
                chunk: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Raw YAML content of plexus.yaml */
                        config: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp of last modification
                         */
                        lastModified: string;
                        /** @description SHA-256 hash for change detection */
                        checksum: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description New YAML content */
                    config: string;
                    /**
                     * @description Validate configuration before applying
                     * @default true
                     */
                    validate?: boolean;
                    /**
                     * @description Hot reload after save
                     * @default true
                     */
                    reload?: boolean;
                };
            };
        };
        responses: {
            /** @description Configuration updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        /** @description SHA-256 of previous configuration */
                        previousChecksum: string;
                        /** @description SHA-256 of new configuration */
                        newChecksum: string;
                        /** @description Present only if validation fails */
                        validationErrors?: string[];
                    };
                };
            };
            /** @description Invalid request or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        message: string;
                        validationErrors?: string[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description State retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        debug: {
                            enabled: boolean;
                            captureRequests: boolean;
                            captureResponses: boolean;
                        };
                        cooldowns: {
                            provider: string;
                            reason: string;
                            /**
                             * Format: int64
                             * @description Unix timestamp in milliseconds
                             */
                            endTime: number;
                            /** @description Remaining seconds */
                            remaining: number;
                        }[];
                        providers: {
                            name: string;
                            enabled: boolean;
                            /** @description True if not on cooldown */
                            healthy: boolean;
                            cooldownRemaining?: number | null;
                            metrics: {
                                /** @description Average latency in milliseconds */
                                avgLatency: number;
                                successRate: number;
                                requestsLast5Min: number;
                            };
                        }[];
                        /** @description Seconds since process start */
                        uptime: number;
                        /** @example 0.8.0 */
                        version: string;
                    };
                };
            };
        };
    };
    updateState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDebugAction"] | components["schemas"]["ClearCooldownsAction"] | components["schemas"]["EnableProviderAction"] | components["schemas"]["DisableProviderAction"];
            };
        };
        responses: {
            /** @description Action completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        state: components["schemas"]["StateGetResponse"];
                    };
                };
            };
            /** @description Unknown action or invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queryLogs: {
        parameters: {
            query?: {
                /** @description Log type to query */
                type?: "usage" | "error" | "trace";
                /** @description Maximum number of entries to return */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
                /** @description Filter by provider name */
                provider?: string;
                /** @description Filter by model name */
                model?: string;
                /** @description Filter by API key name */
                apiKey?: string;
                /** @description Filter by request success status */
                success?: boolean;
                /** @description ISO 8601 timestamp for start of range */
                startDate?: string;
                /** @description ISO 8601 timestamp for end of range */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logs retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "usage" | "error" | "trace";
                        total: number;
                        limit: number;
                        offset: number;
                        hasMore: boolean;
                        /** @description Entries vary based on type parameter */
                        entries: Record<string, never>[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Delete only this type
                     * @enum {string}
                     */
                    type?: "usage" | "error" | "trace";
                    /** @description Delete entries older than N days */
                    olderThanDays?: number;
                    /** @description Delete all log entries */
                    all?: boolean;
                };
            };
        };
        responses: {
            /** @description Logs deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        deleted: {
                            usage: number;
                            error: number;
                            trace: number;
                        };
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLogDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Complete usage log entry */
                        usage: Record<string, never>;
                        /** @description Array of error log entries */
                        errors?: Record<string, never>[];
                        /** @description Array of debug trace entries */
                        traces?: components["schemas"]["DebugTraceEntry"][];
                    };
                };
            };
            /** @description Log entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Too many clients connected (max 10) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
